In [65]:
def loadDataSet():
    postingList = [['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
                  ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
                  ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
                  ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
                  ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
                  ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]
    classVec = [0, 1, 0, 1, 0, 1]    #1 is abusive, 0 not
    return postingList, classVec

In [66]:
def createVocabList(dataSet):
    vocabSet = set([])
    for document in dataSet:
        vocabSet = vocabSet | set(document)
    return list(vocabSet)

In [67]:
def setOfWords2Vec(vocabList, inputSet):
    returnVec = [0] * len(vocabList)
    for word in inputSet:
        if word in vocabList:
            returnVec[vocabList.index(word)] = 1
        else:
            print('the word:%s is not my Vocabulary!' % word)
    return returnVec

In [68]:
listOPosts, listClasses = loadDataSet()
myVocabList = createVocabList(listOPosts)

In [69]:
myVocabList

['not',
 'worthless',
 'my',
 'I',
 'to',
 'is',
 'food',
 'please',
 'has',
 'licks',
 'flea',
 'park',
 'maybe',
 'problems',
 'ate',
 'take',
 'steak',
 'mr',
 'so',
 'cute',
 'dalmation',
 'him',
 'dog',
 'buying',
 'posting',
 'help',
 'garbage',
 'stupid',
 'quit',
 'how',
 'stop',
 'love']

In [70]:
setOfWords2Vec(myVocabList, listOPosts[0])

[0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0]

In [71]:
from numpy import *
def trainNB0(trainMatrix, trainCategory):
    numTrainDocs = len(trainMatrix)    #get the number of documents
    numWords = len(trainMatrix[0])    #get the number of all words
    pAbusive = sum(trainCategory) / float(numTrainDocs)    #p(c): how many time we see the class / the total number
    
    p0Num = ones(numWords)    #build list whose length is numWords
    p1Num = ones(numWords)    #the numerator
    p0Denom = 1.0    #the denominator
    p1Denom = 1.0
    for i in range(numTrainDocs):
        if trainCategory[i] == 1:    #if the class is 1 (abusive)
            p1Num += trainMatrix[i]    #vector
            p1Denom += sum(trainMatrix[i])    #total number of words
        else:
            p0Num += trainMatrix[i]    #if the class is 0
            p0Denom += sum(trainMatrix[i])
    p1Vect = log(p1Num / p1Denom)
    p0Vect = log(p0Num / p0Denom)
    return p0Vect, p1Vect, pAbusive

In [72]:
listOPosts, listClasses = loadDataSet()
myVocabList = createVocabList(listOPosts)
myVocabList
trainMat = []
for postinDoc in listOPosts:
    trainMat.append(setOfWords2Vec(myVocabList, postinDoc))
trainMat

[[0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0],
 [1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0],
 [0,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1],
 [0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  0],
 [0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0],
 [0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0]]

In [73]:
p0V, p1V, pAb = trainNB0(trainMat, listClasses)

In [74]:
pAb

0.5

In [75]:
p0V

array([-3.21887582, -3.21887582, -1.83258146, -2.52572864, -2.52572864,
       -2.52572864, -3.21887582, -2.52572864, -2.52572864, -2.52572864,
       -2.52572864, -3.21887582, -3.21887582, -2.52572864, -2.52572864,
       -3.21887582, -2.52572864, -2.52572864, -2.52572864, -2.52572864,
       -2.52572864, -2.12026354, -2.52572864, -3.21887582, -3.21887582,
       -2.52572864, -3.21887582, -3.21887582, -3.21887582, -2.52572864,
       -2.52572864, -2.52572864])

In [76]:
p1V

array([-2.30258509, -1.89711998, -2.99573227, -2.99573227, -2.30258509,
       -2.99573227, -2.30258509, -2.99573227, -2.99573227, -2.99573227,
       -2.99573227, -2.30258509, -2.30258509, -2.99573227, -2.99573227,
       -2.30258509, -2.99573227, -2.99573227, -2.99573227, -2.99573227,
       -2.99573227, -2.30258509, -1.89711998, -2.30258509, -2.30258509,
       -2.99573227, -2.30258509, -1.60943791, -2.30258509, -2.99573227,
       -2.30258509, -2.99573227])

In [171]:
def classifyNB(vec2Classify, p0Vec, p1Vec, pClass1):
    p1 = sum(vec2Classify * p1Vec) + log(pClass1)
    #print(vec2Classify * p1Vec)
    p0 = sum(vec2Classify * p0Vec) + log(1.0 - pClass1)
    if p1 > p0:
        return 1
    else:
        return 0

In [173]:
def testingNB():
    listOPosts, listClasses = loadDataSet()    #get the documents and their classes
    myVocabList = createVocabList(listOPosts)    #create a list includes all words
    trainMat = []
    for postinDoc in listOPosts:
        trainMat.append(setOfWords2Vec(myVocabList, postinDoc))    #output vectors of 1s and 0s: train matrix
    p0V, p1V, pAb = trainNB0(array(trainMat), array(listClasses))    #conditional probabilities
    testEntry = ['love', 'my', 'dalmation']
    thisDoc = array(setOfWords2Vec(myVocabList, testEntry))    #output vectors of 1s and 0s
    #print(thisDoc)
    print(testEntry, 'calssified as: ', classifyNB(thisDoc, p0V, p1V, pAb))
    testEntry = ['stupid', 'garbage']
    thisDoc = array(setOfWords2Vec(myVocabList, testEntry))    #output vectors of 1s and 0s
    #print(thisDoc)
    print(testEntry, 'calssified as: ', classifyNB(thisDoc, p0V, p1V, pAb))

In [174]:
testingNB()

[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1]
['love', 'my', 'dalmation'] calssified as:  0
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0]
['stupid', 'garbage'] calssified as:  1


In [80]:
def bagOfWords2VecMN(vocabList, inputSet):
    returnVec = [0] * len(vocabList)
    for word in inputSet:
        if word in vocabList:
            returnVec[vocabList.index(word)] += 1
    return returnVec

In [81]:
#4.6 Example classifying spam email with naive bayes
import re
mySent = 'This book is the best nook on Python or M.L. I have ever laid eyes upon.'
regEx = re.compile('\W')
listOfTokens = regEx.split(mySent)
listOfTokens

['This',
 'book',
 'is',
 'the',
 'best',
 'nook',
 'on',
 'Python',
 'or',
 'M',
 'L',
 '',
 'I',
 'have',
 'ever',
 'laid',
 'eyes',
 'upon',
 '']

In [82]:
[tok.lower() for tok in listOfTokens if len(tok) > 0]

['this',
 'book',
 'is',
 'the',
 'best',
 'nook',
 'on',
 'python',
 'or',
 'm',
 'l',
 'i',
 'have',
 'ever',
 'laid',
 'eyes',
 'upon']

In [83]:
emailText = open('email/ham/6.txt').read()
listOfTokens = regEx.split(emailText)

In [84]:
def textParse(bigString):
    import re
    listOfTokens = re.split('\W', bigString)
    return [tok.lower() for tok in listOfTokens if len(tok) > 2]

In [85]:
def spamTest():
    docList = []; classList = []; fullText = []
    #create docList, fullText and every doc's class
    for i in range(1, 26):
        wordList = textParse(open('email/spam/%d.txt' % i).read())
        docList.append(wordList)
        fullText.extend(wordList)
        classList.append(1)
        wordList1 = textParse(open('email/ham/%d.txt' % i).read())
        docList.append(wordList1)
        fullText.extend(wordList1)
        classList.append(0)
    
    #create vocabList
    vocabList = createVocabList(docList)
    
    #create trainingSet randomly
    trainingSet = [i for i in range(50)]; testSet = []
    for i in range(10):
        randIndex = int(random.uniform(0, len(trainingSet)))
        testSet.append(trainingSet[randIndex])
        trainingSet.pop(randIndex)
        
    #create trainMat and their classes
    trainMat = []; trainClasses = []
    for docIndex in trainingSet:
        trainMat.append(setOfWords2Vec(vocabList, docList[docIndex]))
        trainClasses.append(classList[docIndex])
        
    #frequency and p(c)
    p0V, p1V, pSpam = trainNB0(array(trainMat), array(trainClasses))
    
    #test
    errorCount = 0
    for docIndex in testSet:
        wordVector = setOfWords2Vec(vocabList, docList[docIndex])
        if classifyNB(array(wordVector), p0V, p1V, pSpam) != classList[docIndex]:
            errorCount += 1
    print('the error rate is: ', float(errorCount)/len(testSet))

In [86]:
spamTest()

[-0.         -0.         -0.         -4.13316455 -0.         -0.
 -0.         -4.42084663 -0.         -0.         -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -4.42084663 -0.         -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -4.42084663 -0.         -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.
 -4.42084663 -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         

In [115]:
import feedparser
ny = feedparser.parse('https://newyork.craigslist.org/search/ccc?format=rss')
sf = feedparser.parse('https://sfbayarea.craigslist.org/search/ccc?format=rss')
#ny = feedparser.parse('https://newyork.craigslist.org/search/act?query=friend&sort=rel?format=rss')
#ny = feedparser.parse('https://sfbay.craigslist.org/d/local-news-and-views/search/vnn?format=rss')
#ny = feedparser.parse('https://sfbay.craigslist.org/d/small-biz-ads/search/biz?format=rss')
sf

{'feed': {'title': 'craigslist SF bay area | community search',
  'title_detail': {'type': 'text/plain',
   'language': None,
   'base': 'https://sfbay.craigslist.org/search/ccc?format=rss',
   'value': 'craigslist SF bay area | community search'},
  'links': [{'rel': 'alternate',
    'type': 'text/html',
    'href': 'https://sfbay.craigslist.org/search/ccc'}],
  'link': 'https://sfbay.craigslist.org/search/ccc',
  'subtitle': '',
  'subtitle_detail': {'type': 'text/html',
   'language': None,
   'base': 'https://sfbay.craigslist.org/search/ccc?format=rss',
   'value': ''},
  'language': 'en-us',
  'rights': 'copyright 2018 craigslist',
  'rights_detail': {'type': 'text/plain',
   'language': None,
   'base': 'https://sfbay.craigslist.org/search/ccc?format=rss',
   'value': 'copyright 2018 craigslist'},
  'publisher': 'robot@craigslist.org',
  'publisher_detail': {'email': 'robot@craigslist.org'},
  'authors': [{'email': 'robot@craigslist.org'}],
  'author': 'robot@craigslist.org',
  '

In [116]:
ny['entries']
len(ny['entries'])

25

In [118]:
sf['entries'][9]

{'id': 'https://sfbay.craigslist.org/sfc/com/d/looking-for-horse-loving-philanthropists/6766579932.html',
 'title': 'Looking for horse loving philanthropists (Nor Cal)',
 'title_detail': {'type': 'text/plain',
  'language': None,
  'base': 'https://sfbay.craigslist.org/search/ccc?format=rss',
  'value': 'Looking for horse loving philanthropists (Nor Cal)'},
 'links': [{'rel': 'alternate',
   'type': 'text/html',
   'href': 'https://sfbay.craigslist.org/sfc/com/d/looking-for-horse-loving-philanthropists/6766579932.html'}],
 'link': 'https://sfbay.craigslist.org/sfc/com/d/looking-for-horse-loving-philanthropists/6766579932.html',
 'summary': 'Established, legitimate 501(c)(3) nonprofit Northern CA horse rescue recently acquired land for relocating the organization and is seeking funding to assist with development of new rescue, rehab and training/education facility for domestic and wild h ...',
 'summary_detail': {'type': 'text/html',
  'language': None,
  'base': 'https://sfbay.craigsli

In [165]:
def calcMostFreq(vocabList, fullText):
    import operator
    freqDict = {}
    for token in vocabList:
        freqDict[token] = fullText.count(token)
    sortedFreq = sorted(freqDict.items(), key = operator.itemgetter(1), reverse = True)
    return sortedFreq[:23]

In [166]:
def localWords(feed1, feed0):
    import feedparser
    docList = []; classList = []; fullText = []
    minLen = min(len(feed1['entries']), len(feed0['entries']))
    #create docList, fullText and every doc's class
    for i in range(minLen):
        wordList = textParse(feed1['entries'][i]['summary'])
        docList.append(wordList)
        fullText.extend(wordList)
        classList.append(1)
        wordList = textParse(feed0['entries'][i]['summary'])
        docList.append(wordList)
        fullText.extend(wordList)
        classList.append(0)
        
    #create vocabList and find the top 30 words
    vocabList = createVocabList(docList)
    top30Words = calcMostFreq(vocabList, fullText)
    
    #delete the top 30 words from vocabList
    for pairW in top30Words:
        if pairW[0] in vocabList:
            vocabList.remove(pairW[0])
            
    #create testSet and trainingSet randomly
    trainingSet = [i for i in range(2 * minLen)]; testSet = []
    for i in range(20):
        randIndex = int(random.uniform(0, len(trainingSet)))
        testSet.append(trainingSet[randIndex])
        del(trainingSet[randIndex])
        
    #
    trainMat = []; trainClasses = []
    for docIndex in trainingSet:
        trainMat.append(bagOfWords2VecMN(vocabList, docList[docIndex]))    #将训练集中的每一条数据，转化为词向量
        trainClasses.append(classList[docIndex])
    p0V, p1V, pSpam = trainNB0(array(trainMat), array(trainClasses))
    
    
    errorCount = 0
    for docIndex in testSet:
        wordVector = bagOfWords2VecMN(vocabList, docList[docIndex])
        if classifyNB(array(wordVector), p0V, p1V, pSpam) != classList[docIndex]:
            errorCount += 1
    print('the error rate is: ', float(errorCount) / len(testSet))
    return vocabList, p0V, p1V

In [167]:
#ny = feedparser.parse('https://newyork.craigslist.org/d/small-biz-ads/search/biz?format=rss')
#sf = feedparser.parse('https://sfbay.craigslist.org/d/small-biz-ads/search/biz?format=rss')
ny = feedparser.parse('https://newyork.craigslist.org/search/ccc?format=rss')
sf = feedparser.parse('https://sfbayarea.craigslist.org/search/ccc?format=rss')
vocabList, pSF, pNY = localWords(ny, sf)

[ -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -5.75890177  -0.          -0.          -0.
  -0.          -5.75890177  -0.          -5.75890177  -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.         

In [168]:
vocabList, pSF, pNY = localWords(ny, sf)

[ -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -6.09130988  -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -5.3981627   -0.          -0.          -0.          -0.
  -0.          -0.          -0.          -0.          -0.
  -0.         

In [169]:
import operator
def getTopWords(ny, sf):
    vocabList, p0V, p1V = localWords(ny, sf)
    topNY = []
    topSF = []
    for i in range(len(p0V)):
        if p0V[i] > -4.4: topSF.append((vocabList[i], p0V[i]))
        if p1V[i] > -4.4: topNY.append((vocabList[i], p1V[i]))
    sortedSF = sorted(topSF, key = lambda pair: pair[1], reverse = True)
    print('SF*SF*SF*SF')
    for item in sortedSF:
        print(item[0])
    sortedNY = sorted(topNY, key = lambda pair: pair[1], reverse = True)
    print('NY*NY*NY*NY')
    for item in sortedNY:
        print(item[0])

In [164]:
getTopWords(ny, sf)

[-0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -5.6094718
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.         -5.6094718  -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.  