In [24]:
import kNN
import numpy
datingDataMat, datingLabels = kNN.file2matrix('datingTestSet2.txt')
normMat, ranges, minVals = kNN.autoNorm(datingDataMat)

In [25]:
normMat

array([[0.44832535, 0.39805139, 0.56233353],
       [0.15873259, 0.34195467, 0.98724416],
       [0.28542943, 0.06892523, 0.47449629],
       ...,
       [0.29115949, 0.50910294, 0.51079493],
       [0.52711097, 0.43665451, 0.4290048 ],
       [0.47940793, 0.3768091 , 0.78571804]])

In [26]:
ranges

array([9.1273000e+04, 2.0919349e+01, 1.6943610e+00])

minVals

In [27]:
minVals

array([0.      , 0.      , 0.001156])

In [28]:
def datingClassTest():
    hoRatio = 0.10
    datingDataMat, datingLabels = kNN.file2matrix('datingTestSet2.txt')
    normMat, ranges, minVals = kNN.autoNorm(datingDataMat)
    m = normMat.shape[0]
    numTestVecs = int(m*hoRatio)
    errorCount = 0.0
    for i in range(numTestVecs):
        classifierResult = kNN.classify0(normMat[i,:],normMat[numTestVecs:m,:],datingLabels[numTestVecs:m],3)
        str1 =  "the classifier came back with: %d, the real answer is: %d" % (classifierResult, datingLabels[i])
        print(str1)
        if (classifierResult != datingLabels[i]): errorCount += 1.0
    str2 = "the total error rate is: %f" % (errorCount/float(numTestVecs))
    print(str2)
    return (errorCount/float(numTestVecs))

In [29]:
a = datingClassTest()

the classifier came back with: 3, the real answer is: 3
the classifier came back with: 2, the real answer is: 2
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 3, the real answer is: 3
the classifier came back with: 3, the real answer is: 3
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 3, the real answer is: 3
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 2, the real answer is: 2
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answe

In [34]:
def classifyPerson():
    resultList = ['not at all','in small doses','in large doses']
    percentTats = float(input("percentage of time spent playing video game?"))
    ffMiles = float(input("frequent flier miles earned per year?"))
    iceCream = float(input("liters of ice cream comsumed per year?"))
    datingDataMat, datingLabels = kNN.file2matrix('datingTestSet2.txt')
    normMat, ranges, minVals = kNN.autoNorm(datingDataMat)
    inArr = numpy.array([ffMiles, percentTats, iceCream])
    classifierResult = kNN.classify0((inArr-minVals)/ranges,normMat,datingLabels,3)
    str3 = "You will probably like this person: ", resultList[classifierResult-1]
    print(str3)

In [35]:
b = classifyPerson()

percentage of time spent playing video game?0
frequent flier miles earned per year?10000
liters of ice cream comsumed per year?0.5
('You will probably like this person: ', 'in small doses')
